name: Build/release

on:
  push:
    branches:
      - master

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
          with:
            node-version: '12'

      - run: npm run publish:gh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
          with:
            node-version: '12'
      - run: npm run publish:gh:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install package
      - run: sudo apt-get install -y rpm bsdtar

      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
          with:
            node-version: '12'
      - run: npm run publish:gh:linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
